version: '3.7'
services:

    dovefix:
      image: r0nam1/dovefix:latest
      container_name: dovefix
      environment:
        - TZ=America/Los_Angles
      volumes:
        # Certificate locations
        - /applications/certificates/:/certificates
        # Where to store the acutal mail files
        - ./mail:/mailDir
        # To make sure DNS, hostname and all that are what we want.
        - /etc/hosts:/etc/hosts
        - /etc/hostname:/etc/hostname
        - /etc/resolv.conf:/etc/resolv.conf
        # Dovecot editable configs.
        - ./dovecot-etc:/etc/dovecot
        # Dovecot log files, does not empty itself!
        - ./dovecot.log:/var/log/dovecot/dovecot.log
        # Postfix log files, does not emoty itself!
        - ./postfix.log:/var/log/postfix.log
        # Postfix editable configs.
        - ./postfix-etc:/etc/postfix
        # DKIM keys for security.
        - ./dkim-keys:/dkim-keys
      networks:
        dovefix-network:
          ipv4_address: 172.28.0.40
      ports:
        # SMTP Incoming For Other Mail Servers
        - "25:25"
        # IMAP non SSL 
        - "143:143"
        # SMTP non SSL
        - "587:587"
        # SMTP TLS
        - "465:465"
      restart: unless-stopped
      # Container will only start after these two start
      depends_on:
       - rspamd
       - dovefix-mariadb

    # SPAM Filter Milter, using rspamd
    # rSpamd also deals with dkimKeys instead of dovefix
    rspamd:
      image: a16bitsysop/rspamd:3.1-r4-alpine3.15.0-r0
      container_name: rspamd
      environment:
        - TIMEZONE=America/Los_Angles
        - REDIS=redis
      networks:
          dovefix-network:
            ipv4_address: 172.28.0.20
      volumes:
        - ./rspamd/var:/var/lib/rspamd
        - ./rspamd/override.d:/etc/rspamd/override.d
        - ./rspamd/dkimKeys:/dkimKeys
      restart: unless-stopped
      ports:
        # Web interface
        - "11334:11334"
      depends_on:
        - redis

    # Redis for rSpamd
    redis:
      image: redis:6.0
      container_name: redis
      networks:
        dovefix-network:
          ipv4_address: 172.28.0.30
      restart: unless-stopped

    # MariaDB Container for virtual mailbox data
    # Easiest way to host userdata for postfix and dovecot, even if source of truth is LDAP, can easily make replication script to copy
    # pertinant data
    dovefix-mariadb:
      image: mariadb:11.3.1-rc
      environment:
        MYSQL_ROOT_PASSWORD: "rootPass"
        MYSQL_DATABASE: dovefix
        MYSQL_USER: dovefix
        MYSQL_PASSWORD: "userPass"
      volumes:
        - ./dovefix-mariadb/data:/var/lib/mysql
      networks:
        dovefix-network:
          ipv4_address: 172.28.0.90
      restart: unless-stopped

# Contain all this into single network
networks:
  dovefix-network:
    external: true
    name: dovefix-network